# Libraries

In [4]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Logistic Regression Class

In [5]:
class LogisticRegression:
    def __init__(self, x):
        self.theta = np.random.randn(x.shape[1] + 1)  # Generate random weights
    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))
    def gradientDescent(self, x, y, alpha=0.01):
        h = self.sigmoid(np.dot(x, self.theta.T))     # hypothesis
        error = h - y
        self.theta -= alpha * (1 / len(y)) * np.dot(x.T, error)
    def cost(self, x, y):  
        h = self.sigmoid(np.dot(x, self.theta.T))  # hypothesis
        return (-1) * np.sum(y * np.log(h) + (1 - y) * np.log(1 - h))
    def predictClass(self, x):
        x = np.column_stack((x, np.ones((x.shape[0]))))     # Add bias term during prediction
        h = self.sigmoid(np.dot(x, self.theta.T))     # hypothesis
        return np.where(h >= 0.5, 1, 0)
    def predictConfidence(self, x):
        return self.sigmoid(np.dot(x, self.theta.T))
    def getWeights(self):
        return self.theta
    def train(self, x, y, alpha=0.01, numIters=1000, printInterval=20):
        x = np.column_stack((x, np.ones((x.shape[0]))))  #Add bias term for training by adding extra column at the end of x
        for i in range(numIters):
            self.gradientDescent(x, y)
            if printInterval is not None and i % printInterval == 0:
                loss = self.cost(x, y)  
                print(f"Iteration: {i}, Loss: {loss:.4f}")
        probabilities = self.predictConfidence(x)             #probabilities and weights after training
        print("\nProbabilities of x examples belonging to the class:\n",probabilities)
        print("\nFinal weights:\n",self.theta, "\n")


# Loading Iris Dataset

In [6]:
iris = load_iris()
X = iris.data
y = iris.target
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

# Training the Model using One-vs-All approach

In [7]:
accuracies = []
for i in range(3):
    yBinary = np.where(y == i, 1, 0)
    xTrain, xTest, yTrain, yTest = train_test_split(X, yBinary, test_size=0.2, random_state=42)
    model = LogisticRegression(xTrain)
    model.train(xTrain, yTrain)

    yPred = model.predictClass(xTest)
    accuracy = accuracy_score(yTest, yPred)
    accuracies.append(accuracy)

    print(f"\nAccuracy for class {i+1}: {accuracy:.4f}\n")


Iteration: 0, Loss: 127.9264
Iteration: 20, Loss: 106.9436
Iteration: 40, Loss: 93.1329
Iteration: 60, Loss: 81.1521
Iteration: 80, Loss: 70.9063
Iteration: 100, Loss: 62.2676
Iteration: 120, Loss: 55.0426
Iteration: 140, Loss: 49.0155
Iteration: 160, Loss: 43.9795
Iteration: 180, Loss: 39.7524
Iteration: 200, Loss: 36.1820
Iteration: 220, Loss: 33.1445
Iteration: 240, Loss: 30.5407
Iteration: 260, Loss: 28.2917
Iteration: 280, Loss: 26.3350
Iteration: 300, Loss: 24.6207
Iteration: 320, Loss: 23.1088
Iteration: 340, Loss: 21.7672
Iteration: 360, Loss: 20.5698
Iteration: 380, Loss: 19.4956
Iteration: 400, Loss: 18.5271
Iteration: 420, Loss: 17.6498
Iteration: 440, Loss: 16.8518
Iteration: 460, Loss: 16.1231
Iteration: 480, Loss: 15.4553
Iteration: 500, Loss: 14.8410
Iteration: 520, Loss: 14.2743
Iteration: 540, Loss: 13.7500
Iteration: 560, Loss: 13.2634
Iteration: 580, Loss: 12.8107
Iteration: 600, Loss: 12.3886
Iteration: 620, Loss: 11.9940
Iteration: 640, Loss: 11.6244
Iteration: 660

# Final Accuracy of the Model

In [8]:
print(f"Average test accuracy: {np.mean(accuracies):.2f}")

Average test accuracy: 0.89


---

**Note:** I have tried my best to provide accurate results in this notebook. However, these results may not be entirely accurate, and contributions or corrections are encouraged. Thank you!
